package hvqzao.rewrite;

import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JSplitPane;
import javax.swing.JTable;

public class TokenRewriteOptions extends javax.swing.JPanel {

    /**
     * Creates new form TokenRewriteOptions
     */
    public TokenRewriteOptions() {
        initComponents();
    }

    public JButton getAddToken() {
        return addToken;
    }

    public JButton getEditToken() {
        return editToken;
    }

    public JButton getRemoveToken() {
        return removeToken;
    }

    public JTable getTokensTable() {
        return TokensTable;
    }

    public JSplitPane getTokensTableSplitPane() {
        return tokensTableSplitPane;
    }
    
    public JButton getOptionsDefaults() {
        return optionsDefaults;
    }

    public JButton getOptionsHelp() {
        return optionsHelp;
    }

    public JPanel getOptionsRewritePanel() {
        return optionsRewritePanel;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsHelp = new javax.swing.JButton();
        optionsDefaults = new javax.swing.JButton();
        optionsRewritePanel = new javax.swing.JPanel();
        optionsRewriteTitle = new javax.swing.JLabel();
        optionsRewriteDescription = new javax.swing.JLabel();
        addToken = new javax.swing.JButton();
        editToken = new javax.swing.JButton();
        removeToken = new javax.swing.JButton();
        tokensTableSplitPane = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        TokensTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        optionsHelp.setMargin(new java.awt.Insets(0, 0, 0, 0));
        optionsHelp.setMaximumSize(new java.awt.Dimension(24, 24));
        optionsHelp.setMinimumSize(new java.awt.Dimension(24, 24));
        optionsHelp.setPreferredSize(new java.awt.Dimension(24, 24));

        optionsDefaults.setMargin(new java.awt.Insets(0, 0, 0, 0));
        optionsDefaults.setMaximumSize(new java.awt.Dimension(24, 24));
        optionsDefaults.setMinimumSize(new java.awt.Dimension(24, 24));
        optionsDefaults.setPreferredSize(new java.awt.Dimension(24, 24));

        optionsRewriteTitle.setText("<html><b style='color:#e58900;font-size:10px'>Token Rewrite</b></html>");

        optionsRewriteDescription.setText("<html>This extension allows you to get arbitrary value from responses and inject them into future requests. Those can be CSRF tokens, one-time codes etc.</html>");

        addToken.setText("Add");

        editToken.setText("Edit");

        removeToken.setText("Remove");

        tokensTableSplitPane.setDividerLocation(400);
        tokensTableSplitPane.setDividerSize(10);

        TokensTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TokensTable);

        tokensTableSplitPane.setLeftComponent(jScrollPane1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );

        tokensTableSplitPane.setRightComponent(jPanel1);

        javax.swing.GroupLayout optionsRewritePanelLayout = new javax.swing.GroupLayout(optionsRewritePanel);
        optionsRewritePanel.setLayout(optionsRewritePanelLayout);
        optionsRewritePanelLayout.setHorizontalGroup(
            optionsRewritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsRewritePanelLayout.createSequentialGroup()
                .addComponent(optionsRewriteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(optionsRewritePanelLayout.createSequentialGroup()
                .addGroup(optionsRewritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsRewriteDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(optionsRewritePanelLayout.createSequentialGroup()
                        .addGroup(optionsRewritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(editToken, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addToken, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeToken, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tokensTableSplitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        optionsRewritePanelLayout.setVerticalGroup(
            optionsRewritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsRewritePanelLayout.createSequentialGroup()
                .addComponent(optionsRewriteTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionsRewriteDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(optionsRewritePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(optionsRewritePanelLayout.createSequentialGroup()
                        .addComponent(addToken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editToken)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeToken))
                    .addComponent(tokensTableSplitPane, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsHelp, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(optionsDefaults, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(optionsRewritePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(optionsRewritePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionsHelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionsDefaults, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TokensTable;
    private javax.swing.JButton addToken;
    private javax.swing.JButton editToken;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton optionsDefaults;
    private javax.swing.JButton optionsHelp;
    private javax.swing.JLabel optionsRewriteDescription;
    private javax.swing.JPanel optionsRewritePanel;
    private javax.swing.JLabel optionsRewriteTitle;
    private javax.swing.JButton removeToken;
    private javax.swing.JSplitPane tokensTableSplitPane;
    // End of variables declaration//GEN-END:variables
}
